Realisation of task3, homework 2
EvgenyBelichkov/EPAM_HW pull request #11
Opened 2021-03-10 20:17 UTC by EvgenyBelichkov

Can your check my code?
The task is: "Write a function that takes K lists as arguments and returns all possible lists of K items where the first element is from the first list, the second is from the second and so one. You may assume that that every list contain at least one element"
Thank you in advance.

2021-03-18 19:56 UTC, i-n-samartsev commented
Исправь тесты

2021-03-27 19:12 UTC, i-n-samartsev requested changes
надо исправить конфликты

2021-03-27 19:12 UTC, i-n-samartsev commented on homework2/task03/tests/test_of_possible_combinations.py
> +def fixture():
ну я же говорил исправить подход к фикстурам. Семен Семеныч..

2021-04-01 14:21 UTC, closed without merging

2021-04-01 14:21 UTC, EvgenyBelichkov commented
Code will be recommited