Hw03 task03
EvgenyBelichkov/EPAM_HW pull request #17
Opened 2021-03-15 08:14 UTC by EvgenyBelichkov

Can you check my code?
The task is "the task is correction bugs it initial code"
Thank you!

2021-03-18 19:54 UTC, i-n-samartsev commented
не забудь про кейсы с ошибками которые мы разобрали на звонке
1) что будет если запросить фильтр по полю которого нет (или который есть но только в одном словаре)
2) как бороться что выводится всегда последняя запись из 2 возможных.

2021-03-27 19:11 UTC, i-n-samartsev commented
`
def test_against_late_binding():
    data = [ 
       dict(a=1, b=1),
       dict(a=1, b=2)
    ]   
    assert changing_filter.make_filter(b=1, a=1).apply(data) != data
`

добейся чтобы такой код проходил. если не получается, спроси в телеге.

2021-03-27 19:11 UTC, i-n-samartsev requested changes

2021-03-27 19:11 UTC, i-n-samartsev commented on homework3/task03/test/test_of_filter.py
> +    data = fixture
Since you are not changing fixture in any way, you dont need data variable at all.

2021-04-02 09:26 UTC, EvgenyBelichkov commented
> `def test_against_late_binding(): data = [ dict(a=1, b=1), dict(a=1, b=2) ] assert changing_filter.make_filter(b=1, a=1).apply(data) != data`
> 
> добейся чтобы такой код проходил. если не получается, спроси в телеге.

Я проверил предлагаемый тест, он проходит без изменений исходного кода. Если я что-то не так понял - дай знать.

2021-04-03 15:08 UTC, i-n-samartsev commented
Есть конфликт 
Conflicting files
homework3/task03/changing_filter.py

2021-04-12 13:54 UTC, EvgenyBelichkov commented
This pull request closed because of conflicting files.
Changed directory will be recommited.

2021-04-12 13:54 UTC, closed without merging